apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-ventas
  namespace: proyecto-semestral
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back-ventas
  template:
    metadata:
      labels:
        app: back-ventas
    spec:
      containers:
        - name: back-ventas
          image: 637423327509.dkr.ecr.us-east-1.amazonaws.com/back-ventas:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"