apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-despacho
  namespace: proyecto-semestral
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-despacho
  template:
    metadata:
      labels:
        app: front-despacho
    spec:
      containers:
        - name: front-despacho
          image: 076866035318.dkr.ecr.us-east-1.amazonaws.com/front-despacho:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"